### ISSUE TITLE
Crear el History Mapping del proyecto.

### ISSUE THREAD

**Issue by DiegOliveros** [ISWPOLI/Intencion-Horaria#17]
#**Formalizar las historias usando ZemHub.**

- [x] Crear las Épicas.
- [x] Crear las Características
- [x] Crear las historias.
- [x] Asignar tareas a las historias.
- [x] Estimar las historias.
+ [x] Asignar tiempos (Milestones)

**Comment by falasias** [comment]
Falta la estimación de tiempos
